### PR TITLE
Feature/landing page

### PR DESCRIPTION
**Pull request by lo0oleta**
Hello Andrew ,
Thank you for submitting this pull request! I appreciate your contribution and the time and effort you put into it, I am reaching out to ask for your help in reviewing my recent pull request .
Thank you again for your time and consideration.

### CODE REVIEW

**Review by koolamusic — CHANGES_REQUESTED** [review]
image


There is a duplicate image in the `README.md`

**Review by koolamusic — CHANGES_REQUESTED** [review]
There are couple redundant code that does nothing in your codebase.
I would suggest you remove them./

https://github.com/lo0oleta/sunnyside-agency/blob/feature/landingPage/tailwind.config.js#L1 This file 

https://github.com/lo0oleta/sunnyside-agency/blob/50dc0682f24c67efa0bc218656af22bb950430b0/postcss.config.js#L1 This file

and this particular line in your `package.json` https://github.com/lo0oleta/sunnyside-agency/blob/50dc0682f24c67efa0bc218656af22bb950430b0/package.json#L29

**Review by koolamusic — CHANGES_REQUESTED** [review]
image


You should ensure that each section you implement is responsive by default, which isn't something that you have going on here. 

Most of the sections dont look good on mobile

**Comment by koolamusic** [comment]
As a final comment, I am going to suggest that you keep your PR titles as descriptive as possible, Although the branch name suggests that you are working on the landing page. 

Sections of the page have already been designed, but small issues like 

- Testimonials
- Navigation menu (the menu is not clickable and does not have hover or focus states)
image

- responsiveness across all sections. 



I am going to suggest you create an issue for each feature and submit a Pull Request per issue, to keep things in focus, and make it easy to track your progress / work done.

**Comment by koolamusic** [comment]
As an example, I have created a new issue #1 for the Navigation feature

**Comment by lo0oleta** [comment]
I don't know why it appears like this but I checked before doing the
pullRequest and this is how it looked like

**Pull request merged**
